- hosts: webservers 
  become: True
  tasks:
    - name: Install packages
      yum:
        name: "httpd"
        state: "present"
    - name: Deploy static website
      copy:
        src: ~/spring-petclinic
        dest: /home/target
    - name : Run jar file
      shell: "java -jar /home/target/*.jar"
...
